### ISSUE TITLE
I can't start the game

### ISSUE THREAD

**Issue by PesaLmon** [Subcher/Unciv-WWII#3]
When I try to start the game, it looks like this
It happens even with the smallest number of people
![スクリーンショット 2021-04-26 221409](https://user-images.githubusercontent.com/46748395/116088486-dfa3c500-a6dc-11eb-9680-f6a5eb5697ef.png)

**Comment by Subcher** [comment]
It's because the mod was out of date. I'm reworking and the mod should work fine in a few hours
