### ISSUE TITLE
Can't start the game

### ISSUE THREAD

**Issue by Poncow5** [Subcher/Unciv-WWII#6]
![Screenshot_2021-07-11-23-30-15-57](https://user-images.githubusercontent.com/72888366/125202910-19c64100-e2a0-11eb-861d-bf7c114ef456.png)

Doesn't give any unit no settler or anything try with every setting still has same problem

**Comment by Subcher** [comment]
It's because the mod was out of date. I'm reworking and the mod should work fine in a few hours
